version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: knowledge-scout-db
    environment:
      POSTGRES_DB: knowledge_scout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - knowledge-scout-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: knowledge-scout-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/knowledge_scout
      - JWT_SECRET=your-super-secret-jwt-key-here
      - JWT_EXPIRES_IN=7d
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_URL=http://localhost:3000
      - MAX_FILE_SIZE=52428800
      - UPLOAD_PATH=./uploads
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - knowledge-scout-network
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: knowledge-scout-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - knowledge-scout-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  knowledge-scout-network:
    driver: bridge
